import type { ArticleSetting } from "@/lib/classifySetting";

export type CatalogEntry = {
  id: string;
  url: string;
  label: string;
  /** Attribution / license note for debugging. */
  source: "unsplash" | "wikimedia" | "pexels" | "local";
  tags: string[];
  requireAny?: string[];
  settings?: ArticleSetting[];
  /**
   * Safe as a last-resort thematic image when the story is stewardship-related
   * but no niche photo matched. Never use organ-specific scenes here.
   */
  generic?: boolean;
};

/**
 * Curated images for stewardship themes.
 * Each URL must appear only once — duplicates show as repeats on the page.
 * Sources: Unsplash, Wikimedia Commons, Pexels, and local `/brief-images`.
 */
export const STORY_IMAGE_CATALOG: CatalogEntry[] = [
  // ── Oral / pharmacy ──────────────────────────────────────────────
  {
    id: "pills-capsule",
    url: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=80",
    label: "capsules and pills",
    source: "unsplash",
    generic: true,
    requireAny: [
      "pill",
      "pills",
      "capsule",
      "oral",
      "prescribing",
      "prescription",
      "pharmacy",
      "outpatient antibiotic",
      "antibiotic",
      "stewardship",
    ],
    tags: [
      "oral antibiotic",
      "pill",
      "pills",
      "capsule",
      "prescribing",
      "prescription",
      "pharmacy",
      "outpatient",
      "antibiotic",
      "stewardship",
    ],
  },
  {
    id: "pills-scattered-art",
    url: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=1200&q=80",
    label: "colorful capsules still life",
    source: "unsplash",
    generic: true,
    requireAny: ["pill", "capsule", "oral", "prescribing", "antibiotic course", "tablet", "antibiotic"],
    tags: ["capsule", "pill", "oral", "tablet", "prescribing", "medication", "antibiotic"],
  },
  {
    id: "medicine-bottles",
    url: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=80",
    label: "medicine bottles",
    source: "unsplash",
    generic: true,
    requireAny: ["pharmacy", "dispensing", "medication", "outpatient", "community", "pharmacist", "prescribing"],
    tags: [
      "pharmacy",
      "medication",
      "dispensing",
      "outpatient",
      "community",
      "retail pharmacy",
      "pharmacist",
      "prescribing",
    ],
    settings: ["community"],
  },
  {
    id: "pharmacy-shelves",
    url: "https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=1200&q=80",
    label: "pharmacy shelves",
    source: "unsplash",
    requireAny: ["pharmacy", "dispensing", "community", "outpatient", "prescription"],
    tags: ["pharmacy", "dispensing", "community", "outpatient", "prescription"],
    settings: ["community"],
  },
  {
    id: "blister-pack",
    url: "https://images.unsplash.com/photo-1550572017-edd951aa8ef6?auto=format&fit=crop&w=1200&q=80",
    label: "medication blister pack",
    source: "unsplash",
    generic: true,
    requireAny: ["oral", "tablet", "course", "outpatient", "prescribing", "antibiotic", "stewardship"],
    tags: ["tablet", "oral", "medication", "prescribing", "antibiotic", "outpatient"],
  },
  {
    id: "wikimedia-penicillin",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Penicillin_culture.jpg/1280px-Penicillin_culture.jpg",
    label: "penicillin culture plate",
    source: "wikimedia",
    requireAny: ["penicillin", "beta-lactam", "culture", "microbiology"],
    tags: ["penicillin", "culture", "microbiology", "antibiotic history", "beta-lactam"],
  },

  // ── IV / hospital drugs ──────────────────────────────────────────
  {
    id: "antibiotic-vials",
    url: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=1200&q=80",
    label: "glass medication vials",
    source: "unsplash",
    requireAny: ["vial", "intravenous", "infusion", "injection", "parenteral", "broad-spectrum"],
    tags: ["vial", "injection", "intravenous", "infusion", "parenteral", "inpatient antibiotic"],
    settings: ["hospital"],
  },
  {
    id: "iv-drip",
    url: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=80",
    label: "IV infusion line",
    source: "unsplash",
    requireAny: [
      "intravenous",
      "infusion",
      "parenteral",
      "inpatient",
      "bacteremia",
      "blood culture",
      "catheter",
      "central line",
    ],
    tags: [
      "intravenous",
      "infusion",
      "inpatient",
      "hospital",
      "blood culture",
      "bacteremia",
      "catheter",
      "central line",
    ],
    settings: ["hospital"],
  },
  {
    id: "syringe-ampoules",
    url: "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?auto=format&fit=crop&w=1200&q=80",
    label: "syringe and ampoules",
    source: "unsplash",
    requireAny: ["injection", "syringe", "ampoule", "vaccine", "vaccination", "immunization", "parenteral"],
    tags: ["injection", "syringe", "ampoule", "vaccine", "vaccination", "immunization", "parenteral"],
  },

  // ── Hospital / clinicians ────────────────────────────────────────
  {
    id: "hospital-corridor",
    url: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80",
    label: "hospital corridor light",
    source: "unsplash",
    generic: true,
    requireAny: [
      "hospital",
      "inpatient",
      "ward",
      "nosocomial",
      "healthcare-associated",
      "admission",
      "stewardship",
    ],
    tags: ["hospital", "inpatient", "ward", "nosocomial", "admission", "acute care", "stewardship"],
    settings: ["hospital"],
  },
  {
    id: "hospital-architecture",
    url: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=1200&q=80",
    label: "modern hospital atrium",
    source: "unsplash",
    generic: true,
    requireAny: ["hospital", "facility", "health system", "inpatient", "institution"],
    tags: ["hospital", "facility", "health system", "inpatient"],
    settings: ["hospital"],
  },
  {
    id: "hospital-staff",
    url: "https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?auto=format&fit=crop&w=1200&q=80",
    label: "clinicians in discussion",
    source: "unsplash",
    generic: true,
    requireAny: [
      "clinician",
      "physician",
      "doctor",
      "rounds",
      "stewardship",
      "guideline",
      "multidisciplinary",
      "pharmacist",
    ],
    tags: [
      "clinician",
      "physician",
      "doctor",
      "rounds",
      "guideline",
      "stewardship program",
      "stewardship",
      "multidisciplinary",
      "pharmacist",
    ],
    settings: ["hospital"],
  },
  {
    id: "surgeon-or",
    url: "https://images.unsplash.com/photo-1551190822-a9333d879b1f?auto=format&fit=crop&w=1200&q=80",
    label: "operating room",
    source: "unsplash",
    requireAny: [
      "surgery",
      "surgical",
      "perioperative",
      "prophylaxis",
      "operating",
      "surgical site",
      "ssi",
    ],
    tags: [
      "surgery",
      "surgical",
      "perioperative",
      "prophylaxis",
      "operating room",
      "surgical site infection",
      "ssi",
    ],
    settings: ["hospital"],
  },
  {
    id: "icu-monitor",
    url: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80",
    label: "critical care monitors",
    source: "unsplash",
    requireAny: ["icu", "intensive care", "critical care", "ventilator", "sepsis", "septic shock"],
    tags: ["icu", "intensive care", "critical care", "ventilator", "sepsis", "shock"],
    settings: ["hospital"],
  },
  {
    id: "pexels-stethoscope-desk",
    url: "https://images.pexels.com/photos/4386467/pexels-photo-4386467.jpeg?auto=compress&cs=tinysrgb&w=1200",
    label: "stethoscope on chart",
    source: "pexels",
    generic: true,
    requireAny: ["clinician", "physician", "diagnosis", "consultation", "guideline", "stewardship"],
    tags: ["stethoscope", "clinician", "diagnosis", "consultation", "guideline", "stewardship"],
  },
  {
    id: "white-coat",
    url: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=1200&q=80",
    label: "health professional in scrubs",
    source: "unsplash",
    // Portrait of a clinician — only for profession-focused stories, never as a generic.
    requireAny: [
      "health profession",
      "health professions",
      "healthcare professional",
      "health professional",
      "physician",
      "physicians",
      "doctor",
      "doctors",
      "nurse",
      "nurses",
      "nursing",
    ],
    tags: [
      "health profession",
      "health professions",
      "healthcare professional",
      "physician",
      "physicians",
      "doctor",
      "nurse",
      "nurses",
      "nursing",
    ],
  },

  // ── Community / outpatient ───────────────────────────────────────
  {
    id: "clinic-stethoscope",
    url: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
    label: "clinic stethoscope",
    source: "unsplash",
    requireAny: [
      "clinic",
      "outpatient",
      "primary care",
      "ambulatory",
      "sinusitis",
      "uri",
      "community",
      "stewardship",
    ],
    tags: [
      "clinic",
      "outpatient",
      "primary care",
      "ambulatory",
      "sinusitis",
      "uri",
      "community",
      "stewardship",
    ],
    settings: ["community"],
  },
  {
    id: "emergency-care",
    url: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80",
    label: "emergency department",
    source: "unsplash",
    requireAny: ["emergency department", "emergency room", "triage", "urgent care"],
    tags: ["emergency", "emergency department", "triage", "urgent", "ed visit"],
    settings: ["community"],
  },
  {
    id: "pediatric-care",
    url: "https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80",
    label: "pediatric clinical care",
    source: "unsplash",
    requireAny: [
      "pediatric",
      "paediatric",
      "child",
      "children",
      "infant",
      "otitis",
      "neonatal",
      "nicu",
      "newborn",
    ],
    tags: [
      "pediatric",
      "paediatric",
      "child",
      "children",
      "infant",
      "otitis",
      "neonatal",
      "nicu",
      "newborn",
    ],
    settings: ["community", "hospital"],
  },
  {
    id: "doctor-exam",
    url: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=1200&q=80",
    label: "physician consultation",
    source: "unsplash",
    requireAny: ["consultation", "clinical visit", "diagnosis", "primary care"],
    tags: ["consultation", "physician", "clinical visit", "diagnosis", "exam"],
    settings: ["community"],
  },

  // ── Microbiology / lab ───────────────────────────────────────────
  {
    id: "petri-culture",
    url: "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=1200&q=80",
    label: "bacterial culture plates",
    source: "unsplash",
    requireAny: [
      "microbiology",
      "culture",
      "petri",
      "antibiogram",
      "susceptibility",
      "colony",
      "bacterial",
      "resistance",
    ],
    tags: [
      "microbiology",
      "culture",
      "bacteria",
      "antibiogram",
      "susceptibility",
      "colony",
      "pathogen",
      "resistance",
    ],
  },
  {
    id: "wikimedia-agar-plates",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Agar_plates_with_bacterial_colonies.jpg/1280px-Agar_plates_with_bacterial_colonies.jpg",
    label: "agar plates with colonies",
    source: "wikimedia",
    requireAny: ["culture", "colony", "bacteria", "microbiology", "agar", "pathogen", "antibiogram", "susceptibility"],
    tags: ["agar", "colony", "bacteria", "microbiology", "culture", "pathogen", "antibiogram", "susceptibility"],
  },
  {
    id: "lab-microscope",
    url: "https://images.unsplash.com/photo-1576086213369-97a306d36557?auto=format&fit=crop&w=1200&q=80",
    label: "laboratory microscope",
    source: "unsplash",
    requireAny: ["laboratory", "microbiology", "diagnostic", "pathogen", "susceptibility"],
    tags: ["laboratory", "microbiology", "diagnostic", "pathogen", "assay"],
  },
  {
    id: "lab-pipette",
    url: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80",
    label: "lab pipette work",
    source: "unsplash",
    requireAny: ["molecular", "pcr", "genomic", "sequencing", "pipette", "assay"],
    tags: ["molecular", "pcr", "genomic", "sequencing", "assay", "laboratory research"],
  },
  {
    id: "pexels-lab-tubes",
    url: "https://images.pexels.com/photos/2280571/pexels-photo-2280571.jpeg?auto=compress&cs=tinysrgb&w=1200",
    label: "laboratory sample tubes",
    source: "pexels",
    requireAny: ["resistance", "mrsa", "vre", "cre", "esbl", "mdro", "pathogen"],
    tags: ["resistance", "mrsa", "pathogen", "multidrug", "microbiology", "gram-positive"],
  },

  // ── Long-term care / aging ───────────────────────────────────────
  {
    id: "elder-care",
    url: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80",
    label: "elder care",
    source: "unsplash",
    requireAny: ["elderly", "aging", "nursing home", "long-term", "ltc", "geriatric", "care home"],
    tags: ["elderly", "nursing home", "long-term care", "ltc", "geriatric", "care home"],
    settings: ["long-term care"],
  },
  {
    id: "nurse-patient",
    url: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=1200&q=80",
    label: "nurse with patient",
    source: "unsplash",
    requireAny: ["nurse", "nursing", "bedside", "patient care"],
    tags: ["nurse", "nursing", "bedside", "patient care", "ward care"],
    settings: ["long-term care", "hospital"],
  },
  {
    id: "pexels-elderly-hands",
    url: "https://images.pexels.com/photos/7551643/pexels-photo-7551643.jpeg?auto=compress&cs=tinysrgb&w=1200",
    label: "caring hands elder",
    source: "pexels",
    requireAny: ["elderly", "geriatric", "nursing home", "long-term", "ltc"],
    tags: ["elderly", "geriatric", "nursing home", "long-term care", "care"],
    settings: ["long-term care"],
  },

  // ── Surveillance / data / public health ──────────────────────────
  {
    id: "data-dashboard",
    url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
    label: "data analytics",
    source: "unsplash",
    requireAny: ["surveillance", "audit", "dashboard", "metric", "benchmark", "scorecard", "utilization"],
    tags: ["surveillance", "audit", "dashboard", "metric", "benchmark", "utilization"],
  },
  {
    id: "public-health",
    url: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
    label: "public health planning",
    source: "unsplash",
    requireAny: ["epidemiology", "outbreak", "public health", "population", "national", "policy"],
    tags: ["epidemiology", "outbreak", "public health", "population", "national", "policy"],
  },
  {
    id: "globe-network",
    url: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=1200&q=80",
    label: "global network lights",
    source: "unsplash",
    requireAny: ["global", "international", "worldwide", "lmic", "low-income", "multi-country"],
    tags: ["global", "international", "worldwide", "network", "policy"],
    settings: ["environment"],
  },

  // ── One Health / environment / animals ───────────────────────────
  {
    id: "vet-care",
    url: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1200&q=80",
    label: "companion animals",
    source: "unsplash",
    requireAny: ["veterinary", "animal", "pet", "companion", "one health", "zoonotic"],
    tags: ["veterinary", "animal", "companion animal", "one health", "zoonotic"],
    settings: ["animal"],
  },
  {
    id: "livestock",
    url: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=1200&q=80",
    label: "livestock pasture",
    source: "unsplash",
    requireAny: ["livestock", "cattle", "farm", "agriculture", "food animal"],
    tags: ["livestock", "cattle", "farm", "agriculture", "food animal", "veterinary"],
    settings: ["animal"],
  },
  {
    id: "wastewater",
    url: "https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=1200&q=80",
    label: "water treatment",
    source: "unsplash",
    requireAny: ["wastewater", "effluent", "resistome", "environmental", "sewage"],
    tags: ["wastewater", "effluent", "resistome", "environmental", "sewage", "water treatment"],
    settings: ["environment"],
  },
  {
    id: "wikimedia-one-health",
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/One_Health_Triad.png/1280px-One_Health_Triad.png",
    label: "One Health triad diagram",
    source: "wikimedia",
    requireAny: ["one health", "zoonotic", "human-animal", "interdisciplinary"],
    tags: ["one health", "zoonotic", "interdisciplinary", "animal", "environment"],
    settings: ["animal", "environment"],
  },

  // ── Infection prevention / atmospheric ───────────────────────────
  {
    id: "blue-gloves-art",
    url: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    label: "gloved hands laboratory",
    source: "unsplash",
    requireAny: ["laboratory", "aseptic", "sterile", "infection control", "ppe", "gloves"],
    tags: ["laboratory", "gloves", "aseptic", "infection control", "ppe"],
  },
  {
    id: "light-microscope-art",
    url: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=1200&q=80",
    label: "microscope in soft light",
    source: "unsplash",
    requireAny: ["research", "laboratory", "science", "discovery", "translational"],
    tags: ["research", "laboratory", "science", "microscope", "discovery"],
  },
  {
    id: "pexels-medical-abstract",
    url: "https://images.pexels.com/photos/356040/pexels-photo-356040.jpeg?auto=compress&cs=tinysrgb&w=1200",
    label: "abstract medical blue",
    source: "pexels",
    generic: true,
    requireAny: ["review", "commentary", "editorial", "perspective", "framework", "stewardship"],
    tags: ["review", "commentary", "editorial", "perspective", "framework", "stewardship"],
  },
  {
    id: "hand-hygiene",
    url: "https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?auto=format&fit=crop&w=1200&q=80",
    label: "hand washing",
    source: "unsplash",
    requireAny: [
      "hand hygiene",
      "infection prevention",
      "infection control",
      "washing",
      "ppe",
      "clostridioides",
      "c. difficile",
      "cdiff",
      "isolation",
    ],
    tags: [
      "hand hygiene",
      "infection prevention",
      "infection control",
      "washing",
      "clostridioides",
      "difficile",
      "isolation",
    ],
    settings: ["hospital"],
  },
  {
    id: "dental-care",
    url: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=1200&q=80",
    label: "dental clinical care",
    source: "unsplash",
    requireAny: ["dental", "dentist", "odontogenic", "oral surgery"],
    tags: ["dental", "dentist", "oral", "outpatient", "prophylaxis"],
    settings: ["community"],
  },
  {
    id: "pexels-team-huddle",
    url: "https://images.pexels.com/photos/7089020/pexels-photo-7089020.jpeg?auto=compress&cs=tinysrgb&w=1200",
    label: "care team huddle",
    source: "pexels",
    generic: true,
    requireAny: ["stewardship", "multidisciplinary", "team", "pharmacist", "intervention", "rounds"],
    tags: ["stewardship", "multidisciplinary", "pharmacist", "team", "intervention", "rounds"],
    settings: ["hospital", "community"],
  },
  {
    id: "pexels-oxygen-mask",
    url: "https://images.pexels.com/photos/263402/pexels-photo-263402.jpeg?auto=compress&cs=tinysrgb&w=1200",
    label: "acute respiratory care",
    source: "pexels",
    requireAny: ["pneumonia", "ventilator", "vap", "respiratory failure", "icu"],
    tags: ["pneumonia", "respiratory", "ventilator", "icu", "critical care", "vap"],
    settings: ["hospital"],
  },
  {
    id: "sepsis-urgent",
    url: "https://images.unsplash.com/photo-1581595220892-b0739db3b8c5?auto=format&fit=crop&w=1200&q=80",
    label: "urgent hospital care",
    source: "unsplash",
    requireAny: ["sepsis", "septic", "bacteremia", "bloodstream infection", "septic shock"],
    tags: ["sepsis", "bacteremia", "bloodstream infection", "shock", "critical care"],
    settings: ["hospital"],
  },
  {
    id: "pexels-urine-dipstick",
    url: "https://images.pexels.com/photos/8460157/pexels-photo-8460157.jpeg?auto=compress&cs=tinysrgb&w=1200",
    label: "point-of-care testing",
    source: "pexels",
    requireAny: ["uti", "urinary tract", "cystitis", "pyelonephritis", "urine culture", "bacteriuria"],
    tags: ["uti", "urinary tract infection", "cystitis", "pyelonephritis", "urine culture", "diagnostic"],
    settings: ["community", "hospital", "long-term care"],
  },

  // ── Local topic-specific (filename-guided) ───────────────────────
  {
    id: "local-heart-endocarditis",
    url: "/brief-images/heart-endocarditis.png",
    label: "anatomical heart model",
    source: "local",
    // Organ-specific — never use as generic fallback.
    requireAny: ["heart", "endocarditis", "pericarditis"],
    tags: ["heart", "endocarditis", "pericarditis"],
  },
  {
    id: "local-cold-flu-urti",
    url: "/brief-images/cold-flu-urti.png",
    label: "upper respiratory illness at home",
    source: "local",
    requireAny: [
      "urti",
      "upper respiratory",
      "influenza",
      "flu",
      "common cold",
      "viral respiratory",
      "rhinitis",
      "sinusitis",
      "pharyngitis",
      "otitis",
    ],
    tags: [
      "urti",
      "upper respiratory",
      "influenza",
      "flu",
      "common cold",
      "viral respiratory",
      "sinusitis",
      "pharyngitis",
      "outpatient",
    ],
    settings: ["community"],
  },
  {
    id: "local-medications-antibiotics",
    url: "/brief-images/medications-antibiotics.png",
    label: "oral medications and blister packs",
    source: "local",
    requireAny: [
      "antibiotic",
      "antimicrobial",
      "medication",
      "prescribing",
      "prescription",
      "oral antibiotic",
      "pharmacy",
    ],
    tags: [
      "antibiotic",
      "antimicrobial",
      "medication",
      "prescribing",
      "oral antibiotic",
      "pharmacy",
      "capsule",
      "pill",
    ],
  },
  {
    id: "local-lungs-pneumonia-lrti",
    url: "/brief-images/lungs-pneumonia-lrti.png",
    label: "lungs and lower respiratory pathology",
    source: "local",
    requireAny: [
      "pneumonia",
      "lrti",
      "lower respiratory",
      "lung",
      "hap",
      "vap",
      "cap",
      "bronchitis",
      "respiratory infection",
    ],
    tags: [
      "pneumonia",
      "lower respiratory",
      "lung",
      "lrti",
      "hap",
      "vap",
      "cap",
      "respiratory",
    ],
    settings: ["hospital", "community"],
  },
  {
    id: "local-checklist-assessment",
    url: "/brief-images/checklist-assessment.png",
    label: "electronic clinical assessment",
    source: "local",
    requireAny: [
      "checklist",
      "appropriateness",
      "assessment",
      "criteria",
      "audit",
      "prospective audit",
      "feedback",
      "guideline adherence",
    ],
    tags: [
      "checklist",
      "appropriateness",
      "assessment",
      "audit",
      "criteria",
      "prospective audit",
      "feedback",
      "guideline",
    ],
  },
  {
    id: "local-dental-antibiotic",
    url: "/brief-images/dental-antibiotic.png",
    label: "dental model with antibiotic capsules",
    source: "local",
    requireAny: [
      "dental",
      "dentist",
      "odontogenic",
      "oral surgery",
      "dental prophylaxis",
      "endodontic",
    ],
    tags: [
      "dental",
      "dentist",
      "odontogenic",
      "oral surgery",
      "prophylaxis",
      "antibiotic",
    ],
    settings: ["community"],
  },
  {
    id: "local-ai-ehr-technology",
    url: "/brief-images/ai-ehr-technology.png",
    label: "clinical data and AI workstation",
    source: "local",
    requireAny: [
      "artificial intelligence",
      "machine learning",
      "deep learning",
      "ehr",
      "electronic health",
      "clinical decision",
      "cds",
      "predictive model",
      "informatics",
    ],
    tags: [
      "artificial intelligence",
      "machine learning",
      "ehr",
      "electronic health record",
      "clinical decision support",
      "informatics",
      "predictive",
    ],
  },
  {
    id: "local-dental-clinic",
    url: "/brief-images/dental-clinic.png",
    label: "dental clinic consultation",
    source: "local",
    requireAny: ["dental", "dentist", "odontogenic", "oral health", "dental clinic"],
    tags: ["dental", "dentist", "oral health", "clinic", "outpatient", "consultation"],
    settings: ["community"],
  },
  {
    id: "local-intravenous-bag",
    url: "/brief-images/intravenous-bag.png",
    label: "IV infusion at bedside",
    source: "local",
    requireAny: [
      "intravenous",
      "iv antibiotic",
      "infusion",
      "parenteral",
      "iv therapy",
      "inpatient antibiotic",
    ],
    tags: [
      "intravenous",
      "infusion",
      "parenteral",
      "iv therapy",
      "hospital",
      "inpatient",
    ],
    settings: ["hospital"],
  },
  {
    id: "local-urine-kidney",
    url: "/brief-images/urine-kidney.png",
    label: "urinary system anatomy",
    source: "local",
    requireAny: [
      "uti",
      "urinary tract",
      "kidney",
      "renal",
      "pyelonephritis",
      "cystitis",
      "bacteriuria",
      "urine culture",
      "nephrology",
      "urology",
    ],
    tags: [
      "uti",
      "urinary tract infection",
      "kidney",
      "renal",
      "pyelonephritis",
      "cystitis",
      "bacteriuria",
      "urine culture",
    ],
    settings: ["community", "hospital", "long-term care"],
  },
  {
    id: "local-interprofessional-team",
    url: "/brief-images/interprofessional-team.png",
    label: "interprofessional clinical review",
    source: "local",
    requireAny: [
      "interprofessional",
      "multidisciplinary",
      "pharmacist",
      "stewardship team",
      "care team",
      "rounds",
      "collaboration",
    ],
    tags: [
      "interprofessional",
      "multidisciplinary",
      "pharmacist",
      "stewardship",
      "team",
      "rounds",
      "collaboration",
    ],
    settings: ["hospital", "community"],
  },
  {
    id: "local-blood-microbiology",
    url: "/brief-images/blood-microbiology.png",
    label: "blood specimens in microbiology lab",
    source: "local",
    requireAny: [
      "blood culture",
      "bacteremia",
      "bloodstream",
      "microbiology",
      "specimen",
      "hematology",
      "diagnostic lab",
    ],
    tags: [
      "blood culture",
      "bacteremia",
      "bloodstream infection",
      "microbiology",
      "specimen",
      "laboratory",
      "diagnostic",
    ],
  },
  {
    id: "local-skin-cellulitis",
    url: "/brief-images/skin-cellulitis.png",
    label: "skin soft-tissue anatomy",
    source: "local",
    requireAny: [
      "cellulitis",
      "soft tissue",
      "ssti",
      "skin infection",
      "abscess",
      "erysipelas",
      "dermatology",
      "wound infection",
    ],
    tags: [
      "cellulitis",
      "soft tissue",
      "ssti",
      "skin infection",
      "abscess",
      "wound",
      "dermatology",
    ],
  },
  {
    id: "local-ehr-technology",
    url: "/brief-images/ehr-technology.png",
    label: "clinician working in EHR",
    source: "local",
    requireAny: [
      "ehr",
      "electronic health record",
      "electronic medical record",
      "emr",
      "informatics",
      "clinical decision support",
      "order set",
      "cds",
    ],
    tags: [
      "ehr",
      "electronic health record",
      "informatics",
      "clinical decision support",
      "emr",
      "order set",
    ],
  },
  {
    id: "local-hospital-facility",
    url: "/brief-images/hospital-facility.png",
    label: "modern hospital facility",
    source: "local",
    requireAny: [
      "hospital",
      "inpatient",
      "nosocomial",
      "facility",
      "acute care",
      "tertiary",
    ],
    tags: [
      "hospital",
      "inpatient",
      "nosocomial",
      "facility",
      "acute care",
      "healthcare facility",
    ],
    settings: ["hospital"],
  },

  // ── Local generics (last-resort when no niche match) ─────────────
  {
    id: "local-generic-01",
    url: "/brief-images/generic-01.png",
    label: "healthcare workspace generic",
    source: "local",
    generic: true,
    tags: [],
  },
  {
    id: "local-generic-02",
    url: "/brief-images/generic-02.png",
    label: "clinical pharmacy flat-lay generic",
    source: "local",
    generic: true,
    tags: [],
  },
  {
    id: "local-generic-03",
    url: "/brief-images/generic-03.png",
    label: "hospital care generic",
    source: "local",
    generic: true,
    tags: [],
  },
  {
    id: "local-generic-04",
    url: "/brief-images/generic-04.png",
    label: "medication capsules generic",
    source: "local",
    generic: true,
    tags: [],
  },
  {
    id: "local-generic-05",
    url: "/brief-images/generic-05.png",
    label: "clinical research desk generic",
    source: "local",
    generic: true,
    tags: [],
  },
  {
    id: "local-generic-06",
    url: "/brief-images/generic-06.png",
    label: "pharmaceutical still life generic",
    source: "local",
    generic: true,
    tags: [],
  },
  {
    id: "local-generic-07",
    url: "/brief-images/generic-07.png",
    label: "medical team review generic",
    source: "local",
    generic: true,
    tags: [],
  },
  {
    id: "local-generic-08",
    url: "/brief-images/generic-08.png",
    label: "tablet clinical workflow generic",
    source: "local",
    generic: true,
    tags: [],
  },
  {
    id: "local-generic-09",
    url: "/brief-images/generic-09.png",
    label: "medications on marble generic",
    source: "local",
    generic: true,
    tags: [],
  },
  {
    id: "local-generic-10",
    url: "/brief-images/generic-10.png",
    label: "pills and lab glassware generic",
    source: "local",
    generic: true,
    tags: [],
  },
];
